Set a descriptive name for discovered participants if none is given by the user [#11907]
eProsima/Fast-DDS-statistics-backend pull request #102
Opened 2021-07-01 08:41 UTC by SerranoePros

For the review: Is better to go commit by commit.

2021-07-01 12:54 UTC, JLBuenoLopez-eProsima requested changes

2021-07-01 12:54 UTC, JLBuenoLopez-eProsima commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +    buffer << std::hex << std::setfill('0');
```suggestion
    buffer << std::hex << std::setfill('0');
    for (int i = 0; i < 3; i++)
    {
        buffer << std::setw(2) << static_cast<unsigned>(guid.guidPrefix.value[i + 8]);
        buffer << ".";
    }
```

It is redundant to set again the format of the buffer. Unless you set the flags with other values, the settings persist.

2021-07-01 13:10 UTC, JLBuenoLopez-eProsima commented
The tests added in this PR are issuing `GMOCK WARNING`s. Please, try to get rid of these warnings.

2021-07-02 07:06 UTC, SerranoePros commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +    return "127.0.0.1";
I changed the return to "localhost"

2021-07-02 07:43 UTC, SerranoePros commented on test/unittest/StatisticsParticipantListener/StatisticsParticipantListenerTests.cpp
> +TEST_F(statistics_participant_listener_tests, new_participant_discovered_empty_name_no_locators)
I'm agree, but is not necessary a new test, I added the locators (with a valid IP) with less priority in the `new_participant_discovered_empty_name_"default/metatraffic"_"unicast/multicast"_locator` tests and check that the participant have the name of the most priority locator.

2021-07-02 09:04 UTC, JLBuenoLopez-eProsima reviewed
Some small nitpicks to clarify the comments

2021-07-02 09:15 UTC, JLBuenoLopez-eProsima approved these changes
:+1:

2021-07-02 09:15 UTC, merged