Use UDP transport by default
eProsima/Fast-DDS-statistics-backend pull request #115
Opened 2021-07-19 13:26 UTC by rsanchez15

2021-07-19 13:29 UTC, EduPonz requested changes

2021-07-19 13:29 UTC, EduPonz commented on src/cpp/StatisticsBackend.cpp
> +    /* Workaround to avoid using SHM transport by default */
```suggestion
    /* Avoid using SHM transport by default */
```

2021-07-19 13:37 UTC, rsanchez15 commented on src/cpp/StatisticsBackend.cpp
> +    /* Workaround to avoid using SHM transport by default */
Addressed in 5595df4

2021-07-19 15:01 UTC, IkerLuengo approved these changes
LGTM

2021-07-20 10:19 UTC, rsanchez15 commented
https://github.com/eProsima/Fast-DDS-statistics-backend/pull/115#pullrequestreview-710202429 addressed in c8346e4

2021-07-20 14:31 UTC, IkerLuengo approved these changes
LGTM

2021-07-20 14:32 UTC, merged