New HelloWorldExample [12385]
eProsima/Fast-DDS-statistics-backend pull request #125
Opened 2021-09-14 05:56 UTC by juanlofer-eprosima

2021-10-06 13:18 UTC, jparisu commented on examples/cpp/HelloWorldExample/arg_configuration.h
> +    WAIT,
I would totally remove this argument

2021-10-06 13:30 UTC, jparisu commented on examples/cpp/HelloWorldExample/Monitor.cpp
> +void Monitor::Listener::on_participant_discovery(
**In general** 
I would do specific discovery messages for each entity kind
The `id` here is not relevant to the user, but more like a mess. Add GUID in Participant, Writer and Reader, comment that a new topic has been discovered, mention the physical data when it arrives. In summary, use `get_info` with the new entities and give some information

2021-10-27 08:24 UTC, jparisu submitted a review, later dismissed
LGTM 
uncrustify fails in autogenerated files
test fails in leaky test case

2021-11-19 09:23 UTC, EduPonz commented
@juanlofer-eprosima Can you please rebase this?

2021-11-23 06:24 UTC, jparisu requested changes
LGTM

Please, fix uncrustify

2021-11-23 06:31 UTC, jparisu submitted a review, later dismissed
LGTM 

Uncrustify fails because autogenerated or thirdparty files

2021-11-25 11:30 UTC, merged