[13258] Release notes v0.4.0
eProsima/Fast-DDS-statistics-backend pull request #139
Opened 2021-12-21 07:06 UTC by JLBuenoLopez-eProsima

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

2021-12-21 09:14 UTC, JLBuenoLopez-eProsima commented
CI is failing due to an issue which is explained and solved in #140. This PR should be rebased after that PR is merged.

2021-12-22 06:59 UTC, JLBuenoLopez-eProsima commented
CI failures are unrelated

2021-12-22 09:16 UTC, MiguelCompany requested changes

2021-12-22 09:16 UTC, MiguelCompany commented on docs/rst/notes/notes.rst
> +* Fix deadlock when accessing the database within a callback implementation.
```suggestion
* Fix deadlock when accessing the database within a callback implementation.
* Avoid using deprecated namespace.
* Improvements on CI
```

2021-12-22 09:23 UTC, MiguelCompany submitted a review, later dismissed

2021-12-22 10:21 UTC, MiguelCompany approved these changes
👍

2021-12-22 10:49 UTC, merged