Remove inactive entities
eProsima/Fast-DDS-statistics-backend pull request #177
Opened 2022-10-14 11:03 UTC by jparisu

2022-10-25 12:18 UTC, MiguelCompany requested changes

2022-10-25 14:07 UTC, jparisu commented on test/unittest/Database/DatabaseClearTests.cpp
> +    // TODO
You really don't like TODOs :stuck_out_tongue_closed_eyes:

2022-10-26 06:06 UTC, MiguelCompany requested changes
Just a nit

2022-10-26 06:06 UTC, MiguelCompany commented on src/cpp/database/database.cpp
> +    // only internal map should be iterate.
```suggestion
    // we should just iterate over the internal map.
```

2022-10-26 09:20 UTC, MiguelCompany commented on src/cpp/database/database.cpp
> +                }
I would probably only do this when `active` is `false`.

2022-10-26 09:46 UTC, MiguelCompany requested changes

2022-10-26 09:46 UTC, MiguelCompany commented on include/fastdds_statistics_backend/StatisticsBackend.hpp
> +
These two new API methods need to have tests.

2022-10-26 13:17 UTC, MiguelCompany requested changes
Small nit

2022-10-26 13:17 UTC, MiguelCompany commented on test/unittest/StatisticsBackend/ClearEntitiesTests.cpp
> +// Windows dll do not export ParticipantProxyData class members (private APIs)
```suggestion
// Windows dll does not export ParticipantProxyData / WriterProxyData class members (private APIs)
```

2022-10-26 14:07 UTC, merged