Bump version to v1.0.0
eProsima/Fast-DDS-statistics-backend pull request #220
Opened 2023-12-19 09:56 UTC by jepemi

2023-12-19 14:01 UTC, irenebm requested changes

2023-12-19 14:03 UTC, jepemi commented on versions.md
> +| Foonathan Memory Vendor | [eProsima/foonathan_memory_vendor](https://github.com/eProsima/foonathan_memory_vendor) | [v1.3.1](https://github.com/eProsima/foonathan_memory_vendor/releases/tag/v1.3.1)
Right, to be removed.

2023-12-19 14:06 UTC, jepemi commented on docs/rst/types/status_kind.rst
> +| |DEADLINE_MISSED-api|         | |OK-api|/|ERROR-api|  |
Undo changes

2023-12-19 14:06 UTC, jepemi commented on docs/rst/types/status_kind.rst
> +| |SAMPLE_LOST-api|             | |OK-api|/|ERROR-api|  |
Undo changes

2023-12-19 15:02 UTC, irenebm approved these changes
LGTM

2023-12-20 11:11 UTC, rsanchez15 requested changes

2023-12-20 11:11 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +        - `v2.1.1 <https://github.com/eProsima/Fast-CDR/releases/tag/v2.1.1>`_
I think we should target [Fast CDR v2.1.2](https://github.com/eProsima/Fast-CDR/releases/tag/v2.1.2). Update this everywhere

2023-12-20 11:31 UTC, rsanchez15 approved these changes

2023-12-20 12:00 UTC, merged