Fix OpenSSL version for windows platforms
eProsima/Fast-DDS-statistics-backend pull request #225
Opened 2024-02-06 10:33 UTC by rsanchez15

2024-02-06 10:39 UTC, EduPonz requested changes

2024-02-06 10:39 UTC, EduPonz commented on .github/workflows/test.yml
I'd instead do

```
      - name: Install OpenSSL
        uses: eProsima/eprosima-CI/windows/install_openssl@v0
        with:
          version: '3.1.1'
 ```

2024-02-06 10:42 UTC, rsanchez15 commented on .github/workflows/test.yml
I'd prefer to do that when changing to eProsima CI. Until then this is just a patch.

2024-02-14 11:03 UTC, EduPonz approved these changes

2024-02-14 11:04 UTC, merged