[21458] Add IDL format to topic entities
eProsima/Fast-DDS-statistics-backend pull request #245
Opened 2024-08-27 05:57 UTC by Carlosespicur

This PR allow to save the IDL representation of discovered types in a map, using the type name as key, to avoid unnecessary copies of  the same data (in case of different entities publishing the same data type, for example).

Needed to be merged before:
https://github.com/eProsima/Fast-DDS-statistics-backend/pull/239

2024-09-02 06:18 UTC, JesusPoderoso commented
@Carlosespicur please rebase on top of master

2024-09-10 14:55 UTC, JesusPoderoso requested changes

2024-09-10 14:55 UTC, JesusPoderoso commented on src/cpp/database/database.cpp
> +
Remove extra line break
```suggestion
}

```

2024-09-10 14:55 UTC, JesusPoderoso commented on src/cpp/StatisticsBackend.cpp
> +
Remove extra line break
```suggestion
    }
    Info topic_info = StatisticsBackend::get_info(entity_id);
    return StatisticsBackendData::get_instance()->database_->get_type_idl(topic_info[DATA_TYPE_TAG]);
}

```

2024-09-10 14:55 UTC, JesusPoderoso commented on src/cpp/database/database.cpp
>  }
Remove extra line break
```suggestion
    
    return info;
}
```

2024-09-10 14:55 UTC, JesusPoderoso commented on src/cpp/database/database.hpp
> +
Remove extra line break
```suggestion
```

2024-09-10 14:55 UTC, JesusPoderoso commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +        discovery_info.type_idl = idl.str();
Fix this section identation

2024-09-10 14:55 UTC, JesusPoderoso commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +
Remove extra line break
```suggestion
    monitor_service_status_data_queue_->start_consumer();
```

2024-09-11 09:30 UTC, JesusPoderoso commented on src/cpp/database/database.cpp
> +    }
Pending

2024-09-11 09:30 UTC, JesusPoderoso commented on src/cpp/StatisticsBackend.cpp
> +
Pending

2024-09-11 09:30 UTC, JesusPoderoso commented on src/cpp/database/database.hpp
> +
Pending

2024-09-11 09:30 UTC, JesusPoderoso commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +
Pending

2024-09-12 05:31 UTC, Carlosespicur commented on src/cpp/database/database.cpp
> +    throw BadParameter("Type " + type_name + " not found in the database");
It exists a biunivoque correspondence between type names and type idls, assuming that metatraffic types are ignored and type names without type information are saved with empty strings. When this function is used, not finding the type idl is an unexpected case, but I can return an empty string if it is more convenient.

2024-09-12 06:32 UTC, JesusPoderoso requested changes
Linebreak NITs

2024-09-12 06:32 UTC, JesusPoderoso commented on examples/cpp/HelloWorldExample/Monitor.cpp
>      static_cast<void>(domain_id);
Remove extra line break
```suggestion
{
    static_cast<void>(domain_id);
```

2024-09-12 06:32 UTC, JesusPoderoso commented on src/cpp/database/database.cpp
> +    return (type_idls_.find(type_name) != type_idls_.end());
Remove extra line break
```suggestion
{
    return (type_idls_.find(type_name) != type_idls_.end());
```

2024-09-12 06:32 UTC, JesusPoderoso commented on src/cpp/database/database.cpp
>  }
Remove extra line break
```suggestion
    return info;
}
```

2024-09-12 06:48 UTC, JesusPoderoso approved these changes
LGTM

2024-09-12 09:45 UTC, merged