entity discovery listeners [11093]
eProsima/Fast-DDS-statistics-backend pull request #47
Opened 2021-04-26 08:13 UTC by IkerLuengo

**This PR must be merged after #39**

2021-04-27 15:05 UTC, EduPonz requested changes
A rebase here would me much appreciated

2021-04-30 07:23 UTC, EduPonz requested changes

2021-05-05 13:48 UTC, IkerLuengo commented on src/cpp/CMakeLists.txt
> +    subscriber/StatisticsParticipantListener.cpp
Are they not?

2021-05-05 13:54 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            }
Do you agree removing then:
 - All checks for duplicate insertions
 - All checks for non-existent elements in the hierarchy (inserting a user on a host that is not in the database)
If `insert` is already checking this, I'm OK with it

2021-05-05 13:56 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +                std::shared_ptr<database::Process>(),
Probably that works, as the nullptr will be casted to std::shared_ptr, but I believe this is formally more correct, given the constructor of the DomainParticipant

2021-05-05 13:58 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            // Do nothing
Moving this to a TODO

2021-05-05 13:58 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            // Update QoS on stored entity
Also moved to a TODO, waiting for the feature to be implemented

2021-05-05 14:46 UTC, EduPonz commented on src/cpp/CMakeLists.txt
> +    subscriber/StatisticsParticipantListener.cpp
The entire list is not (at least according to VSCode). I think it puts _ before . for instance.

2021-05-06 05:44 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            process_endpoint_discovery(participant, info, EntityKind::DATAREADER, "DataReader");
absolutely. That was a placeholder meant to be changed, and I forgot. I set the name as the GUID instead.

2021-05-06 12:30 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            locator = std::make_shared<database::Locator>(to_string(dds_locator));
reworked the solution

2021-05-06 12:31 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +    }
removed

2021-05-06 12:43 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +    }
We need the Domain in order to create the Topic. To get the existing Domain, the API makes us get the ID first and the Entity afterwards. In order to be safe, we need to check that the vector of IDs is not empty.

The same with the Participant and the Endpoint itself

2021-05-06 12:50 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            }
I found that we still need to get the Domain to create the Participant, and for that, we need to use `get_entities_by_name`, and to be sure, we have to check it does not return an empty vector.

2021-05-07 11:31 UTC, EduPonz requested changes
I'd remove the tests

statistics_participant_listener_tests.participant_qos_change_discovered
statistics_participant_listener_tests.reader_qos_change_discovered
statistics_participant_listener_tests.writer_qos_change_discovered

They fail because there is no implementation yet, but that' already on the list of pending tasks so we will not forget

2021-05-10 10:19 UTC, IkerLuengo commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            }
Made a design decision: The statistics listeners for each monitor must be unique, and customized for that monitor in the sense that they receive the EntityId of the Domain for which they were created. As these listeners are instantiated by the backend itself, we can control this:
 - When the user creates a new monitor:
   - Create the Domain Entity first in the DB and get the given ID
   - Create the listener, with the given Domain ID
   - Create the statistics endpoints (participant, reader) with the listener

2021-05-11 10:51 UTC, EduPonz requested changes

2021-05-27 13:19 UTC, JLBuenoLopez-eProsima requested changes
A couple of nitpicks.

However, I am concern about the tags being used both in the implementation and in the tests. Would it not be better to define those tags as constants in case that there is a later refactor in some of the QoS? I know it's a lot of work so maybe we can proceed as it is and improve later on.

2021-05-27 13:19 UTC, JLBuenoLopez-eProsima commented on test/unittest/QosSerializer/QosSerializerTests.cpp
> +    TopicDataQosPolicy qos(PID_PAD);
There is no need to pass `PID_PAD` as argument. It is enough with the default constructor. This also applies to the next two tests.

```
    TopicDataQosPolicy qos;
```

2021-05-31 05:56 UTC, JLBuenoLopez-eProsima approved these changes
LGTM with green CI (though the coverage work will probably complain about the updates not yet implemented).

2021-05-31 06:39 UTC, merged