data-to-entity documentation
eProsima/Fast-DDS-statistics-backend pull request #51
Opened 2021-04-29 12:43 UTC by IkerLuengo

2021-04-30 11:54 UTC, EduPonz commented on docs/rst/statistics_backend/statistics_backend.rst
> +    /rst/statistics_backend/get_data_supported_entity_kinds
I think it'd make sense to read this section within the get_data one

2021-04-30 11:54 UTC, EduPonz commented on docs/rst/statistics_backend/statistics_backend.rst
> +    /rst/statistics_backend/get_data_supported_entity_kinds
I think it'd make sense to read this section within the get_data one

2021-05-05 05:55 UTC, EduPonz requested changes

2021-05-05 05:55 UTC, EduPonz commented on docs/code/StatisticsBackendTests.cpp
> +        auto types_list = StatisticsBackend::get_data_supported_entity_kinds(DataKind::DISCOVERY_TIME);
I'd not use `auto`. I think a explicit type is more visual here, since this is the actual documented function

2021-05-05 05:55 UTC, EduPonz commented on docs/code/StatisticsBackendTests.cpp
> +        for (auto types : types_list)
`types` might be a reserved word. You could call it `type_pair` or something like that

2021-05-05 05:55 UTC, EduPonz commented on include/fastdds-statistics-backend/StatisticsBackend.hpp
> +     * i.e. Get the FASTDDS_LATENCY between all the writers in Host1 and all the readers in Host2
I guess this should say `DISCOVERY_TIME`

2021-05-10 14:38 UTC, JLBuenoLopez-eProsima requested changes
When building the project the following Doxygen warning is issued:

```
include/fastdds-statistics-backend/StatisticsBackend.hpp:363: warning: unable to resolve reference to 'Entity' for \ref command
```

This warning applies in several references to `Entity`.

Also, there are two tests directly related to the documentation that are failing:

```
	229 - documentation.doc8 (Failed)
	231 - documentation.spell_check (Failed)
```

Test 229 fails due to `CheckMaxLineLength = 3`.

```
docs/rst/statistics_backend/get_data.rst:75: D001 Line too long
docs/rst/statistics_backend/get_data.rst:80: D001 Line too long
docs/rst/statistics_backend/get_data.rst:83: D001 Line too long
```

The spelling errors are not shown in the Github Action. Running the tests locally:

```
rst/api-reference/statisticsbackend.rst (ofr)
```

2021-05-11 07:44 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2021-05-11 08:18 UTC, merged