[11282] Database select implementation
eProsima/Fast-DDS-statistics-backend pull request #58
Opened 2021-05-10 08:03 UTC by JLBuenoLopez-eProsima

This PR implements and tests the database select methods. It also adds a new overload to the select method to account for the `SAMPLE_DATAS` samples. It modifies the `sample_datas` and `discovered_entity` vectors so they inherit from `StatisticsSample` so the select method can return the pointers to their samples.

2021-05-10 15:30 UTC, IkerLuengo requested changes

2021-05-11 05:32 UTC, JLBuenoLopez-eProsima commented on src/cpp/database/database.cpp
> +                    }
I will add the TODO message and create a task to keep this improvement in mind.

2021-05-11 06:03 UTC, JLBuenoLopez-eProsima commented on test/unittest/Database/DatabaseTests.cpp
> +TEST_F(database_tests, select_fastdds_latency)
Correct. We agree that we do not want to catch any exception letting the application to fail and showing the error as close to the failure as possible. I will add the suggested test checking that it throws if the EntityId is invalid.

2021-05-13 10:24 UTC, IkerLuengo approved these changes
LGTM

2021-05-13 10:26 UTC, merged