Feature/get type [11666]
eProsima/Fast-DDS-statistics-backend pull request #64
Opened 2021-05-31 07:27 UTC by SerranoePros

2021-06-03 10:28 UTC, JLBuenoLopez-eProsima requested changes
After merging #61, a PR can be issued so the `load_database_tests` also use the `DatabaseUtils` auxiliary class.

2021-06-03 10:28 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +
Remove extra blank line

2021-06-03 12:41 UTC, JLBuenoLopez-eProsima commented
Please, complete also the [documentation for this API](https://fast-dds-statistics-backend.readthedocs.io/en/latest/rst/statistics_backend/get_type.html), removing the `Warning` notice and completing any other information you deem necessary.

2021-06-03 13:43 UTC, SerranoePros commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +#include <DatabaseUtils.hpp>
Check when push

2021-06-03 13:59 UTC, SerranoePros commented
> Please, complete also the [documentation for this API](https://fast-dds-statistics-backend.readthedocs.io/en/latest/rst/statistics_backend/get_type.html), removing the `Warning` notice and completing any other information you deem necessary.

Check when push, please.

2021-06-04 08:16 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +#include <DatabaseUtils.hpp>
I should have clarified that the public headers should be before the private ones. And we usually add a blank line between them to distinguish.

2021-06-04 08:20 UTC, JLBuenoLopez-eProsima reviewed
Only a small nitpick

2021-06-04 08:20 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
>  #include <types/types.hpp>
```suggestion
#include <StatisticsBackend.hpp>
#include <types/types.hpp>

#include <database/database.hpp>
#include <DatabaseUtils.hpp>
```

2021-06-04 09:00 UTC, JLBuenoLopez-eProsima reviewed
Sorry, I overlooked this small detail.

2021-06-04 09:00 UTC, JLBuenoLopez-eProsima commented on docs/rst/statistics_backend/get_type.rst
> +Is also possible to retrieve the |EntityKind-api| of an entity given its |EntityId-api|:
```suggestion
It is also possible to retrieve the |EntityKind-api| of an entity given its |EntityId-api|:
```

2021-06-04 09:05 UTC, JLBuenoLopez-eProsima approved these changes
LGTM with green CI

2021-06-04 09:44 UTC, merged