StatisticsBackend::get_entities[11668]
eProsima/Fast-DDS-statistics-backend pull request #66
Opened 2021-06-01 09:03 UTC by SerranoePros

Need to merge main first StatisticsBackend::get_type [11666].

2021-06-04 07:21 UTC, JLBuenoLopez-eProsima requested changes

2021-06-04 07:21 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +}
This test has to be removed. No new API is needed

2021-06-04 07:21 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +TEST_P(statistics_backend_tests, get_entity_ids)
```suggestion
TEST_P(statistics_backend_tests, get_entities)
```

2021-06-04 07:21 UTC, JLBuenoLopez-eProsima commented on include/fastdds-statistics-backend/StatisticsBackend.hpp
> +    static const std::vector<std::shared_ptr<const database::Entity>> get_entities(
We should also complete this documentation stating that this method could throw and in which cases.

2021-06-07 07:20 UTC, SerranoePros commented on src/cpp/database/database.cpp
> +                        break;
I made a rebase of main, but that relation is checked in other pull request currently not merged into main.

2021-06-07 10:40 UTC, JLBuenoLopez-eProsima reviewed
Some small suggestions to improve the documentation

2021-06-07 10:40 UTC, JLBuenoLopez-eProsima commented on test/unittest/TestUtils/DatabaseUtils.hpp
> + * instead is used to insert here a entity with EntityId:all() for use that on several tests.
```suggestion
 * Identifier '0' does not track any entity, instead is used to insert an entity with EntityId:all() for use on several tests.
```

2021-06-07 10:40 UTC, JLBuenoLopez-eProsima commented on src/cpp/database/database.hpp
> +     * is not Entity::all().
```suggestion
     * @throws eprosima::statistics_backend::BadParameter if there is no entity with the given ID or
     * if entity_id is not EntityId::all().
```

It also throws when `entity_kind = EntityKind::INVALID`. Please, complete documentation and take into account this suggestion for other similar comments.

2021-06-07 14:25 UTC, JLBuenoLopez-eProsima reviewed
Please, fix the broken links

2021-06-07 14:25 UTC, JLBuenoLopez-eProsima commented on docs/rst/statistics_backend/get_entities.rst
> +* if the |EntityKind-api| is |EntityKind_INVALID-api|
`|EntityKind-api|` link is broken as well as `|EntityKind_INVALID-api|`

2021-06-07 14:25 UTC, JLBuenoLopez-eProsima commented on docs/rst/statistics_backend/get_entities.rst
> +This call to |get_entities-api| with default value in |EntityId-api| parameter is the same as:
```suggestion
This call to |get_entities-api| is the same as:
```

2021-06-07 14:33 UTC, JLBuenoLopez-eProsima commented on docs/rst/statistics_backend/get_entities.rst
> +* if the |EntityKind-api| is |EntityKind_INVALID-api|
It seems that it is broken because my sphinx version is not updated.

2021-06-08 08:57 UTC, JLBuenoLopez-eProsima requested changes

2021-06-08 08:57 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +        std::cout << entity->id;
Please, remove this debug output.

2021-06-08 08:57 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +        //Check generic info
Leave a space between the `//` and the comment itself

2021-06-08 09:40 UTC, merged