Create locator entities without association to other entities [11705]
eProsima/Fast-DDS-statistics-backend pull request #69
Opened 2021-06-03 07:28 UTC by SerranoePros

-Modified some tests: now the creation and link of a locator is different.
-Database::insert_ddsendpoint_to_locator methods removed, they are no longer needed.

2021-06-07 05:30 UTC, JLBuenoLopez-eProsima commented
This PR needs to be rebased

2021-06-07 08:02 UTC, JLBuenoLopez-eProsima requested changes

2021-06-07 09:32 UTC, SerranoePros commented on src/cpp/database/database.hpp
>          endpoint->data.clear();
Also I modified to insert first in endpoint's collection and then on the other maps, I think it makes sense

2021-06-08 06:47 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM!

2021-06-08 06:53 UTC, JLBuenoLopez-eProsima approved these changes
LGTM!

Rebased to `main` to ensure new changes does not conflict with changes introduced later on `main`. There are no new changes introduced in the rebase.

2021-06-08 07:31 UTC, merged