set domain listener [11472]
eProsima/Fast-DDS-statistics-backend pull request #75
Opened 2021-06-09 14:29 UTC by IkerLuengo

**This PR must be merged after #72**

Start reviewing from the commit with description " Rework listener tests assuming set_domain_listener is implemented "

It has some other improvements and bugfixes that were found during this development and/or testing for coverage:
* Statuses must be updated even if no listener is called
* Parameterize the test for listener calls
* Some bugfixes in other tests

2021-06-16 12:50 UTC, JLBuenoLopez-eProsima requested changes
Also, please look at the following lines from the coverage report:

* https://app.codecov.io/gh/eProsima/Fast-DDS-statistics-backend/compare/75/diff#D1L182: a negative test should be done to check this
* https://app.codecov.io/gh/eProsima/Fast-DDS-statistics-backend/compare/75/diff#D2L200
* https://app.codecov.io/gh/eProsima/Fast-DDS-statistics-backend/compare/75/diff#D2L219
* https://app.codecov.io/gh/eProsima/Fast-DDS-statistics-backend/compare/75/diff#D2L237
* https://app.codecov.io/gh/eProsima/Fast-DDS-statistics-backend/compare/75/diff#D2L255
This last ones are similar and I do not understand why the report says that are not covered. This other similar line is on the other hand covered :man_shrugging: https://app.codecov.io/gh/eProsima/Fast-DDS-statistics-backend/compare/75/diff#D2L287

2021-06-16 12:50 UTC, JLBuenoLopez-eProsima commented on test/unittest/StatisticsBackend/CallingUserListenersTests.cpp
> +        // Set the profile to ignore discovery data from other processes
Remove repeated line

2021-06-16 13:11 UTC, IkerLuengo commented on test/unittest/StatisticsBackend/StatisticsBackendTests.cpp
> +TEST_F(statistics_backend_tests, internal_callbacks_negative_cases)
I commented through the tests, I believe that should be enough, and so the test can be augmented with other (unrelated) negative cases if necessary in the future

2021-06-22 06:43 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2021-06-23 05:37 UTC, JLBuenoLopez-eProsima commented
Windows CI is not building. Please, fix this issue

2021-06-23 09:44 UTC, JLBuenoLopez-eProsima submitted a review, later dismissed
LGTM

2021-06-23 12:55 UTC, JLBuenoLopez-eProsima approved these changes
LGTM.

Windows failure is unrelated.

2021-06-24 08:29 UTC, IkerLuengo commented
@Mergifyio rebase

2021-06-24 08:40 UTC, MiguelCompany commented
@mergifyio rebase

2021-06-25 07:47 UTC, IkerLuengo commented
One testcase is failing:
 statistics_backend_tests.internal_callbacks_negative_cases

2021-06-29 13:19 UTC, JLBuenoLopez-eProsima approved these changes
LGTM :+1:

2021-06-29 13:20 UTC, merged