Metatraffic topic and endpoints [11706]
eProsima/Fast-DDS-statistics-backend pull request #80
Opened 2021-06-11 08:45 UTC by SerranoePros

Need merge first Allow reception of unknown locators [11707].

2021-06-14 14:15 UTC, JLBuenoLopez-eProsima requested changes
Only one comment that deeply affects this PR. The tests should also be adapted taking into account this change.

2021-07-21 14:14 UTC, MiguelCompany requested changes

2021-07-21 14:14 UTC, MiguelCompany commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +            else
Could we keep a reference to the builtin endpoint inside the participant?
This way we could just get the reference here.

2021-07-21 14:14 UTC, MiguelCompany commented on src/cpp/subscriber/StatisticsParticipantListener.cpp
> +                            std::static_pointer_cast<const database::Topic>(database_->get_entity(topic_id.second)));
```suggestion
                        metatraffic_topic = std::const_pointer_cast<database::Topic>(
                            std::static_pointer_cast<const database::Topic>(database_->get_entity(topic_id.second)));
                        break;
```

2021-07-22 08:15 UTC, MiguelCompany approved these changes
LGTM

2021-07-22 08:55 UTC, merged